import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <main className="flex-grow">{children}</main>

        {/* Bottom Navigation */}
        <nav className="fixed bottom-0 left-0 right-0 bg-white border-t shadow-md flex justify-around py-2 z-50 md:hidden">
          <Link href="/dashboard" className="flex flex-col items-center text-sm">
            <span>🏠</span>
            <span>Нүүр</span>
          </Link>
          <Link href="/trip" className="flex flex-col items-center text-sm">
            <span>🧳</span>
            <span>Аяллууд</span>
          </Link>
          <Link href="/profile" className="flex flex-col items-center text-sm">
            <span>👤</span>
            <span>Би</span>
          </Link>
        </nav>
      </body>
    </html>
  );
}
